name: Vitest
on:
  push:
    branches: ["main", "next-release"]
    
  pull_request:
    branches: ["main", "next-release"]
  
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      - uses: pnpm/action-setup@v2
          name: Install pnpm
          with:
            version: 8
            run_install: false
      - name: Install dependencies
        run: pnpm ci
      - name: Run Tests
        run: pnpm run test:unit
      - name: 'Report Coverage'
        if: always() # Also generate the report if tests are failing
        uses:  davelosert/vitest-coverage-report-action@v1
        with:
          json-summary-path: './src/coverage/coverage-summary.json'
          json-final-path: './src/coverage/coverage-final.json'


