name: Vitest
on:
    push:
        branches: ["main", "next-release"]

    pull_request:
        branches: ["main", "next-release"]

    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Setup Node.js environment
            uses: actions/setup-node@v4
            with:
              node-version: 20.x
              cache: npm
              cache-dependency-path: package-lock.json

          - name: Install dependencies
            run: npm ci

          - name: Run Tests
            run: npm run test:unit
